wan: wan0
lans:
- name: lan10
  gateway: 10.10.0.1
  inner_mtu: 8000
- name: lan20
  gateway: 10.20.0.1
  inner_mtu: 8000
tunnel:
  local: 192.0.2.10
  remote: 192.0.2.1
  fib_lookup: true
xdp:
  mode: generic
  decap: true
defaults:
  inner_mtu: 9000
